### ISSUE TITLE
Improve the email notification for proposal valuators

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim#18]
**Initial specification**

When a valuator is selected to comment on a proposal in the backend system, the valuator receives an email notification including a link to the proposal in the backend system.

**Context:**

To assign a valuator, first this user needs to be added into the process as a "process/assembly admin" with the role of "valuator".
Once this is done, valuators can be assigned to individual proposals. This is done by check the checkbox in the list of proposals (admin):
![Screenshot from 2022-09-08 13-37-29](https://user-images.githubusercontent.com/1401520/189113508-3aec5d5e-6ff0-4f3b-9f35-526b569b7597.png)
(choose "assign to valuator")

![Screenshot from 2022-09-08 13-37-45](https://user-images.githubusercontent.com/1401520/189113521-220eefb9-7908-4d48-a55e-330a14b3047a.png)
(press "assign")

Currently, this assigns the "valuator" capability to the assigned user, however this does not generate any notification/email to the user.

**Task**:

- [x] Identify the command that assigns a valuator to the selected proposals
- [x] Create a new mailer job that sends an email to this evaluator with a link to each of the proposals assigned in the admin.
- [x] Add tests for the task

**Email text:**

```
Hi %{name},

You've been assigned by %{admin_name} as a valuator for the proposals listed below. This means you've been trusted to give them feedback and a proper response in the next coming days.

Thanks for your help!

Proposal 1 (link to the decidim admin proposal 1)
Proposal 2 (link to the decidim admin proposal 2)
```

**Methodology**

Start with the branch `release/0.26-stable` and create a PR to `openpoke/decidim` to this very same branch.
