### ISSUE TITLE
Time completion: time elapsed to answer a proposal

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim#36]
**Original request**

As a process-admin, I would like to see the time of completion in the Excel export (as soon as the status changes to completed/accepted).

**Context**

Proposals have a answer `state` and a  `answered_at` time field. In the admin it is possible to see the state but not values on how long it took to answer the proposals (and giving a final state).

**Tasks**

- [ ] Add the time elapsed information in a new method in the proposals model
- [ ] Use this info for answered proposals, show it in the admin?
- [ ] Add this info in a column in the generated CSV/Excel when exporting proposals
- [ ] Tests
